//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatique_task.Pages.Auth
{

    public partial class Login
    {

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblError;

        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.Button btnLogin;

        protected global::System.Web.UI.WebControls.Button btnAdminFill;

        protected global::System.Web.UI.WebControls.Button btnMemberFill;
    }
}
